const cars = [
    {
      id: 1,
      make: 'Tesla',
      model: 'Model S',
      year: 2023,
      price: '$80,000',
      image: 'https://images.unsplash.com/photo-1541899481282-d53b7662ded6?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
      engine: 'Electric',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      fuel_type: 'Electric',
      description: 'The Tesla Model S is a fully electric luxury sedan with cutting-edge technology and impressive performance.',
    },
    {
      id: 2,
      make: 'Ford',
      model: 'Mustang',
      year: 2022,
      price: '$45,000',
      image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
      engine: 'V8',
      transmission: 'Manual',
      drivetrain: 'RWD',
      fuel_type: 'Gasoline',
      description: 'The Ford Mustang is an iconic American muscle car known for its power and style.',
    },
    {
      id: 3,
      make: 'Audi',
      model: 'A4',
      year: 2023,
      price: '$50,000',
      image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
      engine: 'Turbocharged 4-Cylinder',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      fuel_type: 'Gasoline',
      description: 'The Audi A4 is a compact luxury sedan with a perfect blend of performance and comfort.',
    },
    {
      id: 4,
      make: 'BMW',
      model: 'X5',
      year: 2023,
      price: '$65,000',
      image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
      engine: 'Turbocharged 6-Cylinder',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      fuel_type: 'Gasoline',
      description: 'The BMW X5 is a luxury SUV with a sporty design and advanced technology.',
    },
    {
      id: 5,
      make: 'Mercedes-Benz',
      model: 'C-Class',
      year: 2023,
      price: '$55,000',
      image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
      engine: 'Turbocharged 4-Cylinder',
      transmission: 'Automatic',
      drivetrain: 'RWD',
      fuel_type: 'Gasoline',
      description: 'The Mercedes-Benz C-Class is a luxury sedan with a sleek design and premium features.',
    },
    {
      id: 6,
      make: 'Porsche',
      model: '911',
      year: 2023,
      price: '$120,000',
      image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
      engine: 'Turbocharged 6-Cylinder',
      transmission: 'Automatic',
      drivetrain: 'RWD',
      fuel_type: 'Gasoline',
      description: 'The Porsche 911 is a legendary sports car with unmatched performance and style.',
    },
    {
      id: 7,
      make: 'Toyota',
      model: 'Camry',
      year: 2023,
      price: '$30,000',
      image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
      engine: '4-Cylinder',
      transmission: 'Automatic',
      drivetrain: 'FWD',
      fuel_type: 'Gasoline',
      description: 'The Toyota Camry is a reliable and fuel-efficient sedan with a comfortable ride.',
    },
    {
      id: 8,
      make: 'Honda',
      model: 'Civic',
      year: 2023,
      price: '$28,000',
      image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
      engine: '4-Cylinder',
      transmission: 'Automatic',
      drivetrain: 'FWD',
      fuel_type: 'Gasoline',
      description: 'The Honda Civic is a compact car with a sporty design and excellent fuel economy.',
    },
    {
      id: 9,
      make: 'Chevrolet',
      model: 'Corvette',
      year: 2023,
      price: '$70,000',
      image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
      engine: 'V8',
      transmission: 'Automatic',
      drivetrain: 'RWD',
      fuel_type: 'Gasoline',
      description: 'The Chevrolet Corvette is an American sports car with stunning performance and design.',
    },
    {
      id: 10,
      make: 'Jeep',
      model: 'Wrangler',
      year: 2023,
      price: '$40,000',
      image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
      engine: 'V6',
      transmission: 'Automatic',
      drivetrain: '4WD',
      fuel_type: 'Gasoline',
      description: 'The Jeep Wrangler is an off-road SUV with rugged capabilities and a timeless design.',
    },
  ];
  
  export default cars;